Feature/course chapter
blazekv/alexandria-api pull request #11
Opened 2021-07-29 13:49 UTC by Najsr

2021-08-17 17:07 UTC, blazekv requested changes

2021-08-17 17:07 UTC, blazekv commented on app/model/Utils/ChapterHelper.php
> +    public static function orderChapters(array $chapters): array
Lepší asi přejmenovat na sort, pokud je to řadí dle nějakého pořadí, což tak dle kódu vypadá.

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> +     * @Path("/{id}/chapter/{chapterId}")
Nevím jestli jsem to už někde nepsal, ale v REST API bys měl mít uvedenou plurální formu tj. chapters/{id}

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> + * @Path("/course")
Plurální forma viz níže

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> +     * @Path("/{id}/chapter/{chapterId}")
Plurální forma viz výše.

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> +     * @Path("/{id}/chapter/{chapterId}")
Plurální forma viz výše.

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> +     * @Path("/{id}/chapter/{chapterId}/video/{videoId}")
Tady jak video tak chapter - plurální forma

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChapterController.php
> +     * @Path("/{id}/chapter/{chapterId}/video/{videoId}")
Viz výše.

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/CourseController.php
> + * @Path("/course")
Měla by tu být plurální forma

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/ChaptersController.php
> +    public function getAll(ApiRequest $request, ApiResponse $response): ApiResponse
Asi bych udělal spíš jeden kontroller chapters a tam to sjednotil.

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/CourseController.php
> +    public function getAllChapters(ApiRequest $request, ApiResponse $response): ApiResponse
Tohle bych asi spíš přesunul do toho ChaptersControlleru, protože tam bych to čekal víc než tady

2021-08-17 17:07 UTC, blazekv commented on app/module/V1/CoursesController.php
> +use Apitte\Core\Annotation\Controller\Method;
Taky bych asi sjednotil courses a course controller

2021-08-18 13:38 UTC, Najsr commented on app/domain/Api/Facade/ChapterFacade.php
> +        $chapter = $this->entityManager->getChapterRepository()->findOneBy(['id' => $chapterId, 'course' => $courseId]);
Přidal jsem univerzální metody do repozitářů a ty automaticky vyhodí výjimku.

2021-08-18 13:52 UTC, Najsr commented on app/domain/Api/Response/ChapterResponseDto.php
> +            while (($nextChapter = ChapterHelper::findNextChapterVideo($chapterVideos->toArray(), $previousChapter)) !== null) {
Je to řešeno po tomto řádku kódu:
https://github.com/blazekv/alexandria-api/blob/50b6bb0d82afe4e177533486704b4f2df298da9d/app/domain/Api/Facade/ChapterFacade.php#L162
Zároveň pokud odebereš nějaké video uprostřed chapteru, tak se předchůdce převede na jeho potomka (pokud existuje)

2021-08-18 16:12 UTC, Najsr commented on app/domain/Api/Response/ChapterResponseDto.php
> +            while (($nextChapter = ChapterHelper::findNextChapterVideo($chapterVideos->toArray(), $previousChapter)) !== null) {
Cyklická reference zde není možná. U přidávání se akorát ověřuje duplicitní rodič, protože tam nehrozí vytvoření cyklu. Přidal jsem i metodu a endpoint na update a tam to taky není možné. Důvod je ten, že při aktualizaci se předek právě aktualizovávaného převede na potomka. 
Takže pokud bych měl video takto:
A
B
C

a u A nastavil parenta na C, tak to převede na následující tvar:
B
C
A
Důvod je ten, že A mělo null parenta a tak ho zdědilo B.

2021-08-18 16:35 UTC, Najsr commented on app/domain/Api/Response/CourseResponseDto.php
> +            while (($nextChapter = ChapterHelper::findNextChapter($chapters->toArray(), $previousChapter)) !== null) {
Tady to ošetřené nebylo, díky za upozornění. Je to řešené stejně jako u videí.

2021-08-19 11:26 UTC, merged