Feature/bundle coupon
blazekv/alexandria-api pull request #12
Opened 2021-07-30 21:00 UTC by Najsr

2021-08-22 11:10 UTC, blazekv requested changes

2021-08-22 11:10 UTC, blazekv commented on apiary.apib
> +## Bundle course [/bundle/{id}/course/{cid}]
Prosím ještě projdi a zkontroluj ty plurální formy i v Apiary

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/BundleController.php
> + * @Path("/bundle")
Prosím opět plurální formu.

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/BundleController.php
> +     * @Path("/{id}/video/{videoId}")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/BundleController.php
> +     * @Path("/{id}/video/{videoId}")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/BundleController.php
> +     * @Path("/{id}/course/{courseId}")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/BundleController.php
> +     * @Path("/{id}/course/{courseId}")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/CouponController.php
> + * @Path("/coupon")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/CouponsController.php
> +class CouponsController extends BaseV1Controller
Asi bych sloučil jako v předchozím PR do jednoho controlleru.

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/UsersOneController.php
> +     * @Path("/{id}/bundle/{bundleId}")
Plurální formu

2021-08-22 11:10 UTC, blazekv commented on app/module/V1/UsersOneController.php
> +    public function addUserToBundle(ApiRequest $request, ApiResponse $response): ApiResponse
Tohle je zabezpečené na admina že? Aby si to náhodou nemohl provolávat sám user.

2021-08-24 11:39 UTC, Najsr commented on app/module/V1/UsersOneController.php
> +    public function addUserToBundle(ApiRequest $request, ApiResponse $response): ApiResponse
Je to tak, na tento presenter může přistupovat jen a pouze uživatel s rolí Admin.

2021-08-24 12:25 UTC, merged